name: ark-env-micromamba
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - hdf5
  - py-opencv
  - scikit-image=0.19
  - dask
  - dask-image
  - ipydatagrid
  - panel
  - bqplot
  - pip:
    - ark-analysis==0.7.0
    - seaborn
    - seaborn-image
    - opencv-python
    - watchfiles

    - jupyter-scatter[all]
